In [ ]:
pip install tk

Requirement already satisfied: tk in c:\users\rebecca martell\miniconda3\lib\site-packages (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip install pyqt5

Requirement already satisfied: pyqt5 in c:\users\rebecca martell\miniconda3\lib\site-packages (5.12.3)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport
from tkinter import*

In [ ]:
df = pd.read_csv('../data/raw/data.csv',encoding="ISO-8859-1")
df

,UID,Name,Age,Gender,Race,Date,City,State,Manner_of_death,Armed,Mental_illness,Flee
0,133,Karen O. Chin,44.0,Female,Asian,5/4/2000,Alameda,CA,Shot,NaN,False,False
1,169,Chyraphone Komvongsa,26.0,Male,Asian,6/2/2000,Fresno,CA,Shot,NaN,False,False
2,257,Ming Chinh Ly,36.0,Male,Asian,8/13/2000,Rosemead,CA,Shot,Gun,False,False
3,483,Kinh Quoc Dao,29.0,Male,Asian,2/9/2001,Valley Glen,CA,Shot,Gun,False,False
4,655,Vanpaseuth Phaisouphanh,25.0,Male,Asian,6/10/2001,Riverside,CA,Shot,Knife,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
12486,12388,Name withheld by police,NaN,Male,NaN,12/9/2008,Sacramento,CA,Other,NaN,False,False
12487,12429,Gene Lovell Ford,48.0,Male,NaN,8/6/2008,Sacramento,CA,Other,NaN,True,False
12488,12430,Jose Vega,38.0,Male,NaN,8/6/2008,Visalia,CA,Other,NaN,True,False
12489,12636,Humberto Torres,41.0,Male,NaN,3/21/2009,Delano,CA,Other,Gun,False,False
12490,12861,Name withheld by police,39.0,Male,NaN,1/15/2010,Los Angeles,CA,Other,NaN,False,False

In [ ]:
sns.countplot(data=df,y=df['Race'])
plt.show()

C:\Users\Rebecca Martell\AppData\Local\Temp\ipykernel_27364\4259833501.py:2: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()